{
 "title": "Overview of Nodeless Kubernetes Cluster",
 "description": "Nodes, Pods, and Compute Cells in a Nodeless Kubernetes clusster.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource" },
   { "name": "node", "query": "${VAR_NODE}" },
   { "name": "namespace", "query": "${VAR_NAMESPACE}" }
  ]
 },
 "panels": [
  {
   "title": "Number of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Control Plane Node",
   "type": "table",
   "description": "List of Nodes",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_info{container_runtime_version=~\"docker.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "Worker Node with Nodeless Plugin",
   "type": "table",
   "description": "List of Nodes",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_info{container_runtime_version=~\"containerd.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "Nodeless Compute Cells",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"containerd://kiyot.*\"})"
    }
   ]
  },
  {
   "title": "Number of Pods (Running)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods (Running) on Control Plane",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"docker://.*\"})"
    }
   ]
  },
  {
   "title": "Pods (Running) on Worker Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"containerd://.*\", container_id!~\"containerd://kiyot.*\"})"
    }
   ]
  },
  {
   "title": "Pods (Running) on Nodeless Cells",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"containerd://kiyot.*\"})"
    }
   ]
  },
  {
   "title": "Pods (Running) on Control Plane",
   "type": "table",
   "description": "List of pods running on Control Plane",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"docker://.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods (Running) on Worker",
   "type": "table",
   "description": "List of pods running on Pet Worker",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"containerd://.*\", container_id!~\"containerd://kiyot.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods (Running) on Nodeless Cells",
   "type": "table",
   "description": "List of pods running in Nodeless fashion",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container_id=~\"containerd://kiyot.*\"}) by (pod)"
    }
   ]
  }
 ]
}